language: php
php:
  - 5.6
  - 7.0

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev

script:
  - vendor/bin/phpunit --tap tests

notifications:
  email:
    - richellin7@gmail.com

matrix:
  fast_finish: true
